# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('code', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('is_live', models.BooleanField()),
                ('position', models.IntegerField()),
                ('sponsor', models.CharField(max_length=255)),
                ('bg_iphone_updated_at', models.DateTimeField()),
                ('bg_ipad_updated_at', models.DateTimeField()),
                ('bg_iphone_file_size', models.IntegerField()),
                ('bg_ipad_file_size', models.IntegerField()),
                ('bg_iphone_normal', models.URLField()),
                ('bg_iphone_retina', models.URLField()),
                ('bg_ipad_normal', models.URLField()),
                ('bg_ipad_retina', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='exhibition_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition'),
        ),
    ]
