# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('share_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='category_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibition_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='location_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Location'),
        ),
    ]
