# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20160428_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='exhibition_uuid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='category_uuid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='exhibition_uuid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='location_uuid',
        ),
        migrations.AddField(
            model_name='artist',
            name='exhibition',
            field=models.ForeignKey(db_column='exhibition_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(db_column='category_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibition',
            field=models.ForeignKey(db_column='exhibition_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(db_column='location_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Location'),
            preserve_default=False,
        ),
    ]
