# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20160428_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistArtwork',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('artist', models.ForeignKey(db_column='artist_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Artist')),
                ('artwork', models.ForeignKey(db_column='artwork_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Artwork')),
                ('exhibition', models.ForeignKey(db_column='exhibition_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(db_column='artist_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Artist')),
                ('exhibition', models.ForeignKey(db_column='exhibition_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('position', models.IntegerField()),
                ('alt', models.CharField(max_length=255)),
                ('urlThumb', models.URLField()),
                ('urlSmall', models.URLField()),
                ('urlMedium', models.URLField()),
                ('urlLarge', models.URLField()),
                ('urlFull', models.URLField()),
                ('artwork', models.ForeignKey(db_column='artwork_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Artwork')),
                ('exhibition', models.ForeignKey(db_column='exhibition_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tourArtwork',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('position', models.IntegerField()),
                ('artwork', models.ForeignKey(db_column='artwork_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Artwork')),
                ('exhibition', models.ForeignKey(db_column='exhibition_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition')),
                ('tour', models.ForeignKey(db_column='tour_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='artwork',
            field=models.ManyToManyField(through='guide.tourArtwork', to='guide.Artwork'),
        ),
        migrations.AddField(
            model_name='tour',
            name='exhibition',
            field=models.ForeignKey(db_column='exhibition_uuid', on_delete=django.db.models.deletion.CASCADE, to='guide.Exhibition'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artwork',
            field=models.ManyToManyField(through='guide.artistArtwork', to='guide.Artwork'),
        ),
    ]
